// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: types/notification.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Notification_Comment
	//	*Notification_CreatorSubscriber
	//	*Notification_DailyWatchAvailable
	//	*Notification_DailyWatchReminder
	//	*Notification_DeveloperContribute
	//	*Notification_DeveloperRewards
	//	*Notification_DeveloperWelcome
	//	*Notification_FirstSubscription
	//	*Notification_MissedOut
	//	*Notification_NewContent
	//	*Notification_NewLiveStream
	//	*Notification_Reply
	//	*Notification_RewardsApprovalPrompt
	//	*Notification_SaltyExclusive
	//	*Notification_SubscriptionNudge
	//	*Notification_TutorialPublish
	//	*Notification_TutorialSearch
	//	*Notification_TutorialRewards
	//	*Notification_YoutubePending
	//	*Notification_YoutubeTransferred
	Type       isNotification_Type `protobuf_oneof:"type"`
	Name       string              `protobuf:"bytes,1000,opt,name=name,proto3" json:"name,omitempty"`
	Title      string              `protobuf:"bytes,1001,opt,name=title,proto3" json:"title,omitempty"`
	Text       string              `protobuf:"bytes,1002,opt,name=text,proto3" json:"text,omitempty"`
	EmailData  *EmailData          `protobuf:"bytes,1500,opt,name=emailData,proto3" json:"emailData,omitempty"`
	ClaimData  *ClaimData          `protobuf:"bytes,1501,opt,name=claimData,proto3" json:"claimData,omitempty"`
	DeviceData *DeviceData         `protobuf:"bytes,1502,opt,name=deviceData,proto3" json:"deviceData,omitempty"`
	AppData    *AppData            `protobuf:"bytes,1503,opt,name=appData,proto3" json:"appData,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{0}
}

func (m *Notification) GetType() isNotification_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Notification) GetComment() *Comment {
	if x, ok := x.GetType().(*Notification_Comment); ok {
		return x.Comment
	}
	return nil
}

func (x *Notification) GetCreatorSubscriber() *CreatorSubscriber {
	if x, ok := x.GetType().(*Notification_CreatorSubscriber); ok {
		return x.CreatorSubscriber
	}
	return nil
}

func (x *Notification) GetDailyWatchAvailable() *DailyWatchAvailable {
	if x, ok := x.GetType().(*Notification_DailyWatchAvailable); ok {
		return x.DailyWatchAvailable
	}
	return nil
}

func (x *Notification) GetDailyWatchReminder() *DailyWatchReminder {
	if x, ok := x.GetType().(*Notification_DailyWatchReminder); ok {
		return x.DailyWatchReminder
	}
	return nil
}

func (x *Notification) GetDeveloperContribute() *DeveloperContribute {
	if x, ok := x.GetType().(*Notification_DeveloperContribute); ok {
		return x.DeveloperContribute
	}
	return nil
}

func (x *Notification) GetDeveloperRewards() *DeveloperRewards {
	if x, ok := x.GetType().(*Notification_DeveloperRewards); ok {
		return x.DeveloperRewards
	}
	return nil
}

func (x *Notification) GetDeveloperWelcome() *DeveloperWelcome {
	if x, ok := x.GetType().(*Notification_DeveloperWelcome); ok {
		return x.DeveloperWelcome
	}
	return nil
}

func (x *Notification) GetFirstSubscription() *FirstSubscription {
	if x, ok := x.GetType().(*Notification_FirstSubscription); ok {
		return x.FirstSubscription
	}
	return nil
}

func (x *Notification) GetMissedOut() *MissedOut {
	if x, ok := x.GetType().(*Notification_MissedOut); ok {
		return x.MissedOut
	}
	return nil
}

func (x *Notification) GetNewContent() *NewContent {
	if x, ok := x.GetType().(*Notification_NewContent); ok {
		return x.NewContent
	}
	return nil
}

func (x *Notification) GetNewLiveStream() *NewLiveStream {
	if x, ok := x.GetType().(*Notification_NewLiveStream); ok {
		return x.NewLiveStream
	}
	return nil
}

func (x *Notification) GetReply() *Reply {
	if x, ok := x.GetType().(*Notification_Reply); ok {
		return x.Reply
	}
	return nil
}

func (x *Notification) GetRewardsApprovalPrompt() *RewardsApprovalPrompt {
	if x, ok := x.GetType().(*Notification_RewardsApprovalPrompt); ok {
		return x.RewardsApprovalPrompt
	}
	return nil
}

func (x *Notification) GetSaltyExclusive() *SaltyExclusive {
	if x, ok := x.GetType().(*Notification_SaltyExclusive); ok {
		return x.SaltyExclusive
	}
	return nil
}

func (x *Notification) GetSubscriptionNudge() *SubscriptionNudge {
	if x, ok := x.GetType().(*Notification_SubscriptionNudge); ok {
		return x.SubscriptionNudge
	}
	return nil
}

func (x *Notification) GetTutorialPublish() *TutorialPublish {
	if x, ok := x.GetType().(*Notification_TutorialPublish); ok {
		return x.TutorialPublish
	}
	return nil
}

func (x *Notification) GetTutorialSearch() *TutorialSearch {
	if x, ok := x.GetType().(*Notification_TutorialSearch); ok {
		return x.TutorialSearch
	}
	return nil
}

func (x *Notification) GetTutorialRewards() *TutorialRewards {
	if x, ok := x.GetType().(*Notification_TutorialRewards); ok {
		return x.TutorialRewards
	}
	return nil
}

func (x *Notification) GetYoutubePending() *YoutubePending {
	if x, ok := x.GetType().(*Notification_YoutubePending); ok {
		return x.YoutubePending
	}
	return nil
}

func (x *Notification) GetYoutubeTransferred() *YoutubeTransferred {
	if x, ok := x.GetType().(*Notification_YoutubeTransferred); ok {
		return x.YoutubeTransferred
	}
	return nil
}

func (x *Notification) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Notification) GetEmailData() *EmailData {
	if x != nil {
		return x.EmailData
	}
	return nil
}

func (x *Notification) GetClaimData() *ClaimData {
	if x != nil {
		return x.ClaimData
	}
	return nil
}

func (x *Notification) GetDeviceData() *DeviceData {
	if x != nil {
		return x.DeviceData
	}
	return nil
}

func (x *Notification) GetAppData() *AppData {
	if x != nil {
		return x.AppData
	}
	return nil
}

type isNotification_Type interface {
	isNotification_Type()
}

type Notification_Comment struct {
	Comment *Comment `protobuf:"bytes,1,opt,name=comment,proto3,oneof"`
}

type Notification_CreatorSubscriber struct {
	CreatorSubscriber *CreatorSubscriber `protobuf:"bytes,2,opt,name=creatorSubscriber,proto3,oneof"`
}

type Notification_DailyWatchAvailable struct {
	DailyWatchAvailable *DailyWatchAvailable `protobuf:"bytes,3,opt,name=dailyWatchAvailable,proto3,oneof"`
}

type Notification_DailyWatchReminder struct {
	DailyWatchReminder *DailyWatchReminder `protobuf:"bytes,4,opt,name=dailyWatchReminder,proto3,oneof"`
}

type Notification_DeveloperContribute struct {
	DeveloperContribute *DeveloperContribute `protobuf:"bytes,5,opt,name=developerContribute,proto3,oneof"`
}

type Notification_DeveloperRewards struct {
	DeveloperRewards *DeveloperRewards `protobuf:"bytes,6,opt,name=developerRewards,proto3,oneof"`
}

type Notification_DeveloperWelcome struct {
	DeveloperWelcome *DeveloperWelcome `protobuf:"bytes,7,opt,name=developerWelcome,proto3,oneof"`
}

type Notification_FirstSubscription struct {
	FirstSubscription *FirstSubscription `protobuf:"bytes,8,opt,name=firstSubscription,proto3,oneof"`
}

type Notification_MissedOut struct {
	MissedOut *MissedOut `protobuf:"bytes,9,opt,name=missedOut,proto3,oneof"`
}

type Notification_NewContent struct {
	NewContent *NewContent `protobuf:"bytes,10,opt,name=newContent,proto3,oneof"`
}

type Notification_NewLiveStream struct {
	NewLiveStream *NewLiveStream `protobuf:"bytes,11,opt,name=newLiveStream,proto3,oneof"`
}

type Notification_Reply struct {
	Reply *Reply `protobuf:"bytes,12,opt,name=reply,proto3,oneof"`
}

type Notification_RewardsApprovalPrompt struct {
	RewardsApprovalPrompt *RewardsApprovalPrompt `protobuf:"bytes,13,opt,name=rewardsApprovalPrompt,proto3,oneof"`
}

type Notification_SaltyExclusive struct {
	SaltyExclusive *SaltyExclusive `protobuf:"bytes,14,opt,name=saltyExclusive,proto3,oneof"`
}

type Notification_SubscriptionNudge struct {
	SubscriptionNudge *SubscriptionNudge `protobuf:"bytes,15,opt,name=subscriptionNudge,proto3,oneof"`
}

type Notification_TutorialPublish struct {
	TutorialPublish *TutorialPublish `protobuf:"bytes,16,opt,name=tutorialPublish,proto3,oneof"`
}

type Notification_TutorialSearch struct {
	TutorialSearch *TutorialSearch `protobuf:"bytes,17,opt,name=tutorialSearch,proto3,oneof"`
}

type Notification_TutorialRewards struct {
	TutorialRewards *TutorialRewards `protobuf:"bytes,18,opt,name=tutorialRewards,proto3,oneof"`
}

type Notification_YoutubePending struct {
	YoutubePending *YoutubePending `protobuf:"bytes,19,opt,name=youtubePending,proto3,oneof"`
}

type Notification_YoutubeTransferred struct {
	YoutubeTransferred *YoutubeTransferred `protobuf:"bytes,20,opt,name=youtubeTransferred,proto3,oneof"`
}

func (*Notification_Comment) isNotification_Type() {}

func (*Notification_CreatorSubscriber) isNotification_Type() {}

func (*Notification_DailyWatchAvailable) isNotification_Type() {}

func (*Notification_DailyWatchReminder) isNotification_Type() {}

func (*Notification_DeveloperContribute) isNotification_Type() {}

func (*Notification_DeveloperRewards) isNotification_Type() {}

func (*Notification_DeveloperWelcome) isNotification_Type() {}

func (*Notification_FirstSubscription) isNotification_Type() {}

func (*Notification_MissedOut) isNotification_Type() {}

func (*Notification_NewContent) isNotification_Type() {}

func (*Notification_NewLiveStream) isNotification_Type() {}

func (*Notification_Reply) isNotification_Type() {}

func (*Notification_RewardsApprovalPrompt) isNotification_Type() {}

func (*Notification_SaltyExclusive) isNotification_Type() {}

func (*Notification_SubscriptionNudge) isNotification_Type() {}

func (*Notification_TutorialPublish) isNotification_Type() {}

func (*Notification_TutorialSearch) isNotification_Type() {}

func (*Notification_TutorialRewards) isNotification_Type() {}

func (*Notification_YoutubePending) isNotification_Type() {}

func (*Notification_YoutubeTransferred) isNotification_Type() {}

type EmailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email         string            `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Prefix        string            `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Subject       string            `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	EmailTemplate string            `protobuf:"bytes,4,opt,name=emailTemplate,proto3" json:"emailTemplate,omitempty"`
	Placeholders  map[string]string `protobuf:"bytes,5,rep,name=placeholders,proto3" json:"placeholders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EmailData) Reset() {
	*x = EmailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailData) ProtoMessage() {}

func (x *EmailData) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailData.ProtoReflect.Descriptor instead.
func (*EmailData) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{1}
}

func (x *EmailData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailData) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *EmailData) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailData) GetEmailTemplate() string {
	if x != nil {
		return x.EmailTemplate
	}
	return ""
}

func (x *EmailData) GetPlaceholders() map[string]string {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

type ClaimData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title               string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ThumbnailURL        string `protobuf:"bytes,2,opt,name=thumbnailURL,proto3" json:"thumbnailURL,omitempty"`
	ClaimID             string `protobuf:"bytes,3,opt,name=claimID,proto3" json:"claimID,omitempty"`
	Name                string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ChannelName         string `protobuf:"bytes,5,opt,name=channelName,proto3" json:"channelName,omitempty"`
	ChannelClaimID      string `protobuf:"bytes,6,opt,name=channelClaimID,proto3" json:"channelClaimID,omitempty"`
	ChannelThumbnailURL string `protobuf:"bytes,7,opt,name=channelThumbnailURL,proto3" json:"channelThumbnailURL,omitempty"`
}

func (x *ClaimData) Reset() {
	*x = ClaimData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimData) ProtoMessage() {}

func (x *ClaimData) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimData.ProtoReflect.Descriptor instead.
func (*ClaimData) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ClaimData) GetThumbnailURL() string {
	if x != nil {
		return x.ThumbnailURL
	}
	return ""
}

func (x *ClaimData) GetClaimID() string {
	if x != nil {
		return x.ClaimID
	}
	return ""
}

func (x *ClaimData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClaimData) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ClaimData) GetChannelClaimID() string {
	if x != nil {
		return x.ChannelClaimID
	}
	return ""
}

func (x *ClaimData) GetChannelThumbnailURL() string {
	if x != nil {
		return x.ChannelThumbnailURL
	}
	return ""
}

type DeviceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageURL       string            `protobuf:"bytes,4,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Type           string            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Target         string            `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	IsDataOnly     string            `protobuf:"bytes,7,opt,name=isDataOnly,proto3" json:"isDataOnly,omitempty"`
	AnalyticsLabel string            `protobuf:"bytes,8,opt,name=analyticsLabel,proto3" json:"analyticsLabel,omitempty"`
	Placeholders   map[string]string `protobuf:"bytes,9,rep,name=placeholders,proto3" json:"placeholders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DeviceData) Reset() {
	*x = DeviceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceData) ProtoMessage() {}

func (x *DeviceData) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceData.ProtoReflect.Descriptor instead.
func (*DeviceData) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceData) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *DeviceData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeviceData) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DeviceData) GetIsDataOnly() string {
	if x != nil {
		return x.IsDataOnly
	}
	return ""
}

func (x *DeviceData) GetAnalyticsLabel() string {
	if x != nil {
		return x.AnalyticsLabel
	}
	return ""
}

func (x *DeviceData) GetPlaceholders() map[string]string {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

type AppData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AppData) Reset() {
	*x = AppData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppData) ProtoMessage() {}

func (x *AppData) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppData.ProtoReflect.Descriptor instead.
func (*AppData) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{4}
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{5}
}

type CreatorSubscriber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatorSubscriber) Reset() {
	*x = CreatorSubscriber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatorSubscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatorSubscriber) ProtoMessage() {}

func (x *CreatorSubscriber) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatorSubscriber.ProtoReflect.Descriptor instead.
func (*CreatorSubscriber) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{6}
}

type DailyWatchAvailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DailyWatchAvailable) Reset() {
	*x = DailyWatchAvailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyWatchAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyWatchAvailable) ProtoMessage() {}

func (x *DailyWatchAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyWatchAvailable.ProtoReflect.Descriptor instead.
func (*DailyWatchAvailable) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{7}
}

type DailyWatchReminder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DailyWatchReminder) Reset() {
	*x = DailyWatchReminder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyWatchReminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyWatchReminder) ProtoMessage() {}

func (x *DailyWatchReminder) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyWatchReminder.ProtoReflect.Descriptor instead.
func (*DailyWatchReminder) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{8}
}

type DeveloperContribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeveloperContribute) Reset() {
	*x = DeveloperContribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeveloperContribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeveloperContribute) ProtoMessage() {}

func (x *DeveloperContribute) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeveloperContribute.ProtoReflect.Descriptor instead.
func (*DeveloperContribute) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{9}
}

type DeveloperRewards struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeveloperRewards) Reset() {
	*x = DeveloperRewards{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeveloperRewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeveloperRewards) ProtoMessage() {}

func (x *DeveloperRewards) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeveloperRewards.ProtoReflect.Descriptor instead.
func (*DeveloperRewards) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{10}
}

type DeveloperWelcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeveloperWelcome) Reset() {
	*x = DeveloperWelcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeveloperWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeveloperWelcome) ProtoMessage() {}

func (x *DeveloperWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeveloperWelcome.ProtoReflect.Descriptor instead.
func (*DeveloperWelcome) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{11}
}

type FirstSubscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FirstSubscription) Reset() {
	*x = FirstSubscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirstSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstSubscription) ProtoMessage() {}

func (x *FirstSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstSubscription.ProtoReflect.Descriptor instead.
func (*FirstSubscription) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{12}
}

type MissedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MissedOut) Reset() {
	*x = MissedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissedOut) ProtoMessage() {}

func (x *MissedOut) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissedOut.ProtoReflect.Descriptor instead.
func (*MissedOut) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{13}
}

type NewContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewContent) Reset() {
	*x = NewContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContent) ProtoMessage() {}

func (x *NewContent) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContent.ProtoReflect.Descriptor instead.
func (*NewContent) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{14}
}

type NewLiveStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewLiveStream) Reset() {
	*x = NewLiveStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLiveStream) ProtoMessage() {}

func (x *NewLiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLiveStream.ProtoReflect.Descriptor instead.
func (*NewLiveStream) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{15}
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{16}
}

type RewardsApprovalPrompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RewardsApprovalPrompt) Reset() {
	*x = RewardsApprovalPrompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardsApprovalPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardsApprovalPrompt) ProtoMessage() {}

func (x *RewardsApprovalPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardsApprovalPrompt.ProtoReflect.Descriptor instead.
func (*RewardsApprovalPrompt) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{17}
}

type SaltyExclusive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaltyExclusive) Reset() {
	*x = SaltyExclusive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaltyExclusive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaltyExclusive) ProtoMessage() {}

func (x *SaltyExclusive) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaltyExclusive.ProtoReflect.Descriptor instead.
func (*SaltyExclusive) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{18}
}

type SubscriptionNudge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscriptionNudge) Reset() {
	*x = SubscriptionNudge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionNudge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNudge) ProtoMessage() {}

func (x *SubscriptionNudge) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNudge.ProtoReflect.Descriptor instead.
func (*SubscriptionNudge) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{19}
}

type TutorialPublish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TutorialPublish) Reset() {
	*x = TutorialPublish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorialPublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorialPublish) ProtoMessage() {}

func (x *TutorialPublish) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorialPublish.ProtoReflect.Descriptor instead.
func (*TutorialPublish) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{20}
}

type TutorialSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TutorialSearch) Reset() {
	*x = TutorialSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorialSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorialSearch) ProtoMessage() {}

func (x *TutorialSearch) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorialSearch.ProtoReflect.Descriptor instead.
func (*TutorialSearch) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{21}
}

type TutorialRewards struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TutorialRewards) Reset() {
	*x = TutorialRewards{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TutorialRewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorialRewards) ProtoMessage() {}

func (x *TutorialRewards) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorialRewards.ProtoReflect.Descriptor instead.
func (*TutorialRewards) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{22}
}

type YoutubePending struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *YoutubePending) Reset() {
	*x = YoutubePending{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YoutubePending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YoutubePending) ProtoMessage() {}

func (x *YoutubePending) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YoutubePending.ProtoReflect.Descriptor instead.
func (*YoutubePending) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{23}
}

type YoutubeTransferred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *YoutubeTransferred) Reset() {
	*x = YoutubeTransferred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_notification_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YoutubeTransferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YoutubeTransferred) ProtoMessage() {}

func (x *YoutubeTransferred) ProtoReflect() protoreflect.Message {
	mi := &file_types_notification_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YoutubeTransferred.ProtoReflect.Descriptor instead.
func (*YoutubeTransferred) Descriptor() ([]byte, []int) {
	return file_types_notification_proto_rawDescGZIP(), []int{24}
}

var File_types_notification_proto protoreflect.FileDescriptor

var file_types_notification_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0xd6, 0x0c, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x48,
	0x0a, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x13, 0x64, 0x61, 0x69, 0x6c,
	0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x13, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x64, 0x61, 0x69, 0x6c,
	0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x12, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x13, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x13, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x48, 0x00, 0x52, 0x10, 0x64, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x45, 0x0a, 0x10,
	0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x11, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x11, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x09, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12,
	0x33, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x4c, 0x69, 0x76, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x24, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48,
	0x00, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x15, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x48, 0x00, 0x52, 0x15, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x3f,
	0x0a, 0x0e, 0x73, 0x61, 0x6c, 0x74, 0x79, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53,
	0x61, 0x6c, 0x74, 0x79, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52,
	0x0e, 0x73, 0x61, 0x6c, 0x74, 0x79, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x12,
	0x48, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x75, 0x64, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x75, 0x64, 0x67, 0x65, 0x48, 0x00, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x64, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x75, 0x74, 0x6f, 0x72,
	0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x48, 0x00, 0x52, 0x0f, 0x74, 0x75,
	0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x3f, 0x0a,
	0x0e, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x75,
	0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x00, 0x52, 0x0e,
	0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x42,
	0x0a, 0x0f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x48,
	0x00, 0x52, 0x0f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x3f, 0x0a, 0x0e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x48, 0x00, 0x52, 0x0e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x4b, 0x0a, 0x12, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x79, 0x6f,
	0x75, 0x74, 0x75, 0x62, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64,
	0x12, 0x13, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0xe9,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x13, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0xea, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x2f, 0x0a, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0xdc,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18,
	0xdd, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x18, 0xde, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x18, 0xdf, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x61, 0x70, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x09, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3f,
	0x0a, 0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xef, 0x01, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x44, 0x12,
	0x30, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x55, 0x52,
	0x4c, 0x22, 0xa6, 0x02, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x47, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x09, 0x0a, 0x07, 0x41, 0x70,
	0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x09, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x61, 0x69, 0x6c, 0x79, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x22, 0x12, 0x0a,
	0x10, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x69, 0x72, 0x73, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x64,
	0x4f, 0x75, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x50, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x61, 0x6c, 0x74, 0x79, 0x45, 0x78, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x64, 0x67, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x54,
	0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x22, 0x10,
	0x0a, 0x0e, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x22, 0x11, 0x0a, 0x0f, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x62, 0x72, 0x79, 0x69, 0x6f,
	0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_notification_proto_rawDescOnce sync.Once
	file_types_notification_proto_rawDescData = file_types_notification_proto_rawDesc
)

func file_types_notification_proto_rawDescGZIP() []byte {
	file_types_notification_proto_rawDescOnce.Do(func() {
		file_types_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_notification_proto_rawDescData)
	})
	return file_types_notification_proto_rawDescData
}

var file_types_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_types_notification_proto_goTypes = []interface{}{
	(*Notification)(nil),          // 0: types.Notification
	(*EmailData)(nil),             // 1: types.EmailData
	(*ClaimData)(nil),             // 2: types.ClaimData
	(*DeviceData)(nil),            // 3: types.DeviceData
	(*AppData)(nil),               // 4: types.AppData
	(*Comment)(nil),               // 5: types.Comment
	(*CreatorSubscriber)(nil),     // 6: types.CreatorSubscriber
	(*DailyWatchAvailable)(nil),   // 7: types.DailyWatchAvailable
	(*DailyWatchReminder)(nil),    // 8: types.DailyWatchReminder
	(*DeveloperContribute)(nil),   // 9: types.DeveloperContribute
	(*DeveloperRewards)(nil),      // 10: types.DeveloperRewards
	(*DeveloperWelcome)(nil),      // 11: types.DeveloperWelcome
	(*FirstSubscription)(nil),     // 12: types.FirstSubscription
	(*MissedOut)(nil),             // 13: types.MissedOut
	(*NewContent)(nil),            // 14: types.NewContent
	(*NewLiveStream)(nil),         // 15: types.NewLiveStream
	(*Reply)(nil),                 // 16: types.Reply
	(*RewardsApprovalPrompt)(nil), // 17: types.RewardsApprovalPrompt
	(*SaltyExclusive)(nil),        // 18: types.SaltyExclusive
	(*SubscriptionNudge)(nil),     // 19: types.SubscriptionNudge
	(*TutorialPublish)(nil),       // 20: types.TutorialPublish
	(*TutorialSearch)(nil),        // 21: types.TutorialSearch
	(*TutorialRewards)(nil),       // 22: types.TutorialRewards
	(*YoutubePending)(nil),        // 23: types.YoutubePending
	(*YoutubeTransferred)(nil),    // 24: types.YoutubeTransferred
	nil,                           // 25: types.EmailData.PlaceholdersEntry
	nil,                           // 26: types.DeviceData.PlaceholdersEntry
}
var file_types_notification_proto_depIdxs = []int32{
	5,  // 0: types.Notification.comment:type_name -> types.Comment
	6,  // 1: types.Notification.creatorSubscriber:type_name -> types.CreatorSubscriber
	7,  // 2: types.Notification.dailyWatchAvailable:type_name -> types.DailyWatchAvailable
	8,  // 3: types.Notification.dailyWatchReminder:type_name -> types.DailyWatchReminder
	9,  // 4: types.Notification.developerContribute:type_name -> types.DeveloperContribute
	10, // 5: types.Notification.developerRewards:type_name -> types.DeveloperRewards
	11, // 6: types.Notification.developerWelcome:type_name -> types.DeveloperWelcome
	12, // 7: types.Notification.firstSubscription:type_name -> types.FirstSubscription
	13, // 8: types.Notification.missedOut:type_name -> types.MissedOut
	14, // 9: types.Notification.newContent:type_name -> types.NewContent
	15, // 10: types.Notification.newLiveStream:type_name -> types.NewLiveStream
	16, // 11: types.Notification.reply:type_name -> types.Reply
	17, // 12: types.Notification.rewardsApprovalPrompt:type_name -> types.RewardsApprovalPrompt
	18, // 13: types.Notification.saltyExclusive:type_name -> types.SaltyExclusive
	19, // 14: types.Notification.subscriptionNudge:type_name -> types.SubscriptionNudge
	20, // 15: types.Notification.tutorialPublish:type_name -> types.TutorialPublish
	21, // 16: types.Notification.tutorialSearch:type_name -> types.TutorialSearch
	22, // 17: types.Notification.tutorialRewards:type_name -> types.TutorialRewards
	23, // 18: types.Notification.youtubePending:type_name -> types.YoutubePending
	24, // 19: types.Notification.youtubeTransferred:type_name -> types.YoutubeTransferred
	1,  // 20: types.Notification.emailData:type_name -> types.EmailData
	2,  // 21: types.Notification.claimData:type_name -> types.ClaimData
	3,  // 22: types.Notification.deviceData:type_name -> types.DeviceData
	4,  // 23: types.Notification.appData:type_name -> types.AppData
	25, // 24: types.EmailData.placeholders:type_name -> types.EmailData.PlaceholdersEntry
	26, // 25: types.DeviceData.placeholders:type_name -> types.DeviceData.PlaceholdersEntry
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_types_notification_proto_init() }
func file_types_notification_proto_init() {
	if File_types_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatorSubscriber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyWatchAvailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyWatchReminder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeveloperContribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeveloperRewards); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeveloperWelcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FirstSubscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLiveStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewardsApprovalPrompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaltyExclusive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionNudge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorialPublish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorialSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TutorialRewards); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YoutubePending); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_notification_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YoutubeTransferred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_types_notification_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Notification_Comment)(nil),
		(*Notification_CreatorSubscriber)(nil),
		(*Notification_DailyWatchAvailable)(nil),
		(*Notification_DailyWatchReminder)(nil),
		(*Notification_DeveloperContribute)(nil),
		(*Notification_DeveloperRewards)(nil),
		(*Notification_DeveloperWelcome)(nil),
		(*Notification_FirstSubscription)(nil),
		(*Notification_MissedOut)(nil),
		(*Notification_NewContent)(nil),
		(*Notification_NewLiveStream)(nil),
		(*Notification_Reply)(nil),
		(*Notification_RewardsApprovalPrompt)(nil),
		(*Notification_SaltyExclusive)(nil),
		(*Notification_SubscriptionNudge)(nil),
		(*Notification_TutorialPublish)(nil),
		(*Notification_TutorialSearch)(nil),
		(*Notification_TutorialRewards)(nil),
		(*Notification_YoutubePending)(nil),
		(*Notification_YoutubeTransferred)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_notification_proto_goTypes,
		DependencyIndexes: file_types_notification_proto_depIdxs,
		MessageInfos:      file_types_notification_proto_msgTypes,
	}.Build()
	File_types_notification_proto = out.File
	file_types_notification_proto_rawDesc = nil
	file_types_notification_proto_goTypes = nil
	file_types_notification_proto_depIdxs = nil
}
